/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AyoubBani (https://sketchfab.com/AyoubBani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-bar-target-arrow-03e07087107944f8957571f8ce4bcaa4
Title: Game Bar Target Arrow
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

export function Target(props) {
  const { nodes, materials } = useGLTF('/models/target.glb')
  
  return (
    <Float floatIntensity={1}>

      <group {...props} dispose={null}>
        <group scale={0.025}>
          <group position={[5, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_arrow_red_0.geometry}
              material={materials.arrow_red}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_target_white_0.geometry}
              material={materials.target_white}
            />
          </group>
          <group
            position={[101.754, 0.021, -0.037]}
            rotation={[-Math.PI, Math.PI / 2, 0]}
            scale={130.856}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001_arrow_red_0.geometry}
              material={materials.arrow_red}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001_Gold_0.geometry}
              material={materials.Gold}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001_Material002_0.geometry}
              material={materials['Material.002']}
            />
          </group>
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/target.glb')